### PR TITLE
change to support sslcapath, needed for ssl urls

### PR DESCRIPTION
**Pull request by BillKeenan**
failing otherwise on ubuntu 14.04

### CODE REVIEW

**Comment by tfountain** [comment]
You can already use custom HTTP client configuration by configuring the client in advance, so this should work:

    use Zend\Http\Client as HttpClient;
    use Dyn\TrafficManagement;

    $config = array(
        'sslcapath' => '/etc/ssl/certs'
    );
    $httpClient = new HttpClient(null, $config);

    $tm = new TrafficManagement('customerName', 'username', 'password', $httpClient);

This could probably be made a bit more user friendly, but I'd rather not mix and match array configuration with user-defined environment variables, which looks to be what your pull request is doing.

If you have the option, I'd suggest installing the PHP curl extension (`sudo apt-get install php5-curl` on Ubuntu), after which you shouldn't need to do any custom configuration.

**Comment by BillKeenan** [comment]
ah, that sounds proper. i'll give that a go.

**Comment by BillKeenan** [comment]
works a treat.

**Comment by tfountain** [comment]
I've improved this a bit in 0.5.0, so you can now optionally pass array configuration instead of a pre-configured HTTP client instance to the constructor. So the code example above can be simplified to:

```php
use Dyn\TrafficManagement;

$httpConfig = array(
    'sslcapath' => '/etc/ssl/certs'
);
$tm = new TrafficManagement('customerName', 'username', 'password', $httpConfig);
```

**Pull request closed without merging**
